app/chat/__init__.py
"""
Code permettant de définir l'acès aux routes concernant le chat du site.
"""

from flask import Blueprint

chat_bp = Blueprint('chat', __name__)
# Import des routes pour le blueprint chat

from app.chat import routes  

app/chat/routes.py
"""
Code permettant de gérer les routes concernant le chat vidéo du blog.
"""

from datetime import datetime

from app.chat import chat_bp

from flask import render_template, flash, redirect, url_for, request

from app import db

from app.forms.chat_request import ChatRequestForm, UserLink

from app.Models.chat_request import ChatRequest
from app.Models.admin import Admin

from app.mail.routes import send_mail_validate_request, send_mail_refusal_request, send_validate_request, \
    send_confirmation_request_reception, send_request_admin

from app.extensions import create_whereby_meeting_admin


# Route permettant d'afficher la vidéo du chat vidéo.
@chat_bp.route('/video_chat/<int:request_id>')
def video_chat(request_id):
    """
    Route permettant d'ouvrir la page de chat vidéo pour une demande spécifique.

    Cette route affiche la page de chat vidéo uniquement si la demande est validée et que la date/heure du rendez-vous
    est proche de l'heure actuelle. Sinon, elle renvoie une erreur et redirige vers la page d'accueil.

    :param request_id: L'identifiant de la demande de chat vidéo.
    :return: La page HTML contenant l'interface de chat vidéo, si les conditions sont remplies.
    """

    # Récupération de la demande de chat vidéo par son identifiant.
    request = ChatRequest.query.get_or_404(request_id)

    # Vérification de la validation de la demande et si la date/heure du rendez-vous est proche de l'heure actuelle.
    now = datetime.now()
    rdv_datetime = datetime.combine(request.date_rdv, request.heure)

    # Vérification pour autoriser l'accès seulement un jour ou une heure avant le rendez-vous.
    if request.status != 'validée' or rdv_datetime > now:
        flash("Le chat vidéo n'est pas encore disponible ou la demande n'est pas validée.", "error")
        return redirect(url_for('landing_page'))

    return render_template('chat_session_user.html', request=request)


# Route permettant de remplir le formulaire afin de demander un chat vidéo.
@chat_bp.route('/demande-chat-video', methods=['GET', 'POST'])
def chat_request():
    """"
    Affiche le formulaire permettant à l'utilisateur de demander un chat vidéo.

    Cette route est accessible à tous les utilisateurs. Elle instancie le formulaire de demande de chat
    vidéo et le rend disponible à l'utilisateur pour qu'il puisse le remplir.

    :return: Le formulaire de demande de chat vidéo, affiché via le template 'chat/form_request_chat.html'.
    """
    # Instanciation du formulaire.
    formrequest = ChatRequestForm()

    return render_template('chat/form_request_chat.html', formrequest=formrequest)


# Route permettant d'afficher le formulaire de demande de chat
# vidéo et d'enregistrer les informations dans la base de données.
@chat_bp.route('/envoi-demande-chat', methods=['GET', 'POST'])
def send_request():
    """
    Gère la demande de chat vidéo en affichant le formulaire et en enregistrant
    les informations dans la base de données, avec envoi d'emails à l'utilisateur et à l'administrateur.
    """

    formrequest = ChatRequestForm()

    if formrequest.validate_on_submit():
       
        # Récupération des données du formulaire.
        enterprise_name = formrequest.enterprise_name.data
        email = formrequest.email.data
        request_content = formrequest.request_content.data
        date_rdv = formrequest.date_rdv.data
        heure = formrequest.heure.data
        datetime_rdv = datetime.combine(date_rdv, heure)

        # Vérification de la disponibilité de la plage horaire
        conflicting_request = ChatRequest.query.filter_by(date_rdv=date_rdv, heure=heure).first()

        if conflicting_request:
            flash(f"La plage horaire pour le {date_rdv} à {heure} est déjà réservée. Veuillez choisir une autre plage.",
                  "danger")
            return redirect(request.url)
        
        # Récupération de l'administrateur.
        admin = Admin.query.first()
        if not admin:
            flash("Aucun administrateur disponible pour traiter la demande.", "error")
            return redirect(url_for('landing_page'))

        # Création d'une nouvelle demande de chat.
        new_request = ChatRequest(
            enterprise_name=enterprise_name,
            email=email,
            request_content=request_content,
            date_rdv=date_rdv,
            heure=heure,
            admin_id=admin.id
        )
            
        # Tests.    
        try:
            db.session.add(new_request)
            db.session.commit()

            flash("Demande effectuée avec succès.", "success")

        except Exception as e:
            db.session.rollback()
            flash(f"Erreur lors de l'enregistrement de la demande: {str(e)}", "danger")

        # Envoi du mail à l'utilisateur.
        send_confirmation_request_reception(new_request.email, new_request.enterprise_name)

        # Envoi du mail à l'administrateur.
        send_request_admin(new_request.enterprise_name, new_request.request_content)     
        
        return redirect(url_for('chat.user_chat_thanks'))
    
    # En cas d'erreur de validation.
    return render_template('chat/form_request_chat.html', formrequest=formrequest)


# Route pour la page de remerciement
@chat_bp.route("/demande-de-chat-remerciement")
def user_chat_thanks():
    """
    Page affichée après l'envoi réussi d'une demande de chat.
    """
    
    return render_template("chat/chat_form_thanks.html")


# Méthode supprimant la demande de chat vidéo du tableau administrateur.
@chat_bp.route('/suppression-demande-chat/<int:id>', methods=['POST'])
def suppress_chat(id):
    """
    Supprime une demande de chat vidéo du tableau des demandes administratives.

    Cette route permet à l'administrateur de supprimer une demande de chat vidéo spécifique en fonction de son ID.
    Après la suppression, un message de confirmation est affiché et l'administrateur est redirigé vers la page du calendrier
    des demandes de chat.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à supprimer.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après la suppression de la demande.
    """
    # Récupération de la requête à supprimer.
    chat = ChatRequest.query.get(id)

    # Vérification de l'existence de la requête.
    if chat:
        
        # Affichage d'un message avant suppression, incluant le nom de l'entreprise.
        enterprise_name = chat.enterprise_name
        
        # Suppression de la requête.
        db.session.delete(chat)
        # Enregistrement au sein de la base de données.
        db.session.commit()
        flash(f"La requête de l'entreprise : {enterprise_name} a été supprimée.")
        
        # Fermeture de la connexion.
        db.session.close()
        
    return redirect(url_for('admin.calendar'))


# Méthode traitant la demande en attente et la validant.
@chat_bp.route('/validation-demande-chat/<int:id>', methods=['POST'])
def valide_chat(id):
    """
    Valide une demande de chat vidéo spécifique et en informe l'utilisateur par e-mail.

    Cette route permet à un administrateur de valider une demande de chat vidéo en attente, identifiée par son ID.
    Après avoir mis à jour le statut de la demande à "validée", un e-mail de confirmation est envoyé à l'utilisateur
    pour l'informer de la validation.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à valider.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après la validation de la demande.
    """
    # Récupération de la requête à supprimer.
    chat = ChatRequest.query.get(id)
    
    # Vérification de l'existence de la requête.
    if chat:
        try:
            # Récupération de la requête à valider.
            chat = ChatRequest.query.get_or_404(id)

            # Vérification de l'existence de l'utilisateur.
            if not chat:
                flash("Utilisateur non trouvé.", "danger")
                return redirect(url_for("admin.calendar"))

            # Validation de la requête.
            chat.accept_chat_request()
            
            # Envoi du mail de validation de la requête
            send_validate_request(chat)

            flash("La demande de chat vidéo a été traitée et validée.", "success")
        except Exception as e:
            # Gestion erreur si erreur.
            flash(f"Une erreur s'est produite lors de la validation: {str(e)}", "danger")
            return redirect(url_for("admin.calendar"))

    return redirect(url_for("admin.calendar"))


    
# Méthode traitant la demande en attente et la refusant.
@chat_bp.route('/refus-demande-chat/<int:id>', methods=['POST'])
def refuse_chat(id):
    """
    Refuse une demande de chat vidéo spécifique et en informe l'utilisateur par e-mail.

    Cette route permet à un administrateur de refuser une demande de chat vidéo en attente, identifiée par son ID.
    Après avoir mis à jour le statut de la demande à "refusée", un e-mail de notification est envoyé à l'utilisateur
    pour l'informer du refus.

    Args:
        id (int): L'identifiant unique de la demande de chat vidéo à refuser.

    Returns:
        Response: Redirection vers la page du calendrier d'administration après le traitement de la demande.
    """
    # Récupération de la requête à refuser.
    chat = ChatRequest.query.get_or_404(id)

    # Vérification de l'existence de la requête.
    if chat:
        try:
            # Récupération de la requête utilisateur avec les données.
            chat = ChatRequest.query.get_or_404(id)

            # Vérification de l'existence de l'utilisateur.
            if not chat:
                flash("Utilisateur non trouvé.", "danger")
                return redirect(url_for("admin.calendar"))

            # Refus de la requête.
            chat.refuse_chat_request()
            # Envoi du mail de refus.
            send_mail_refusal_request(chat)

templates/chat/chat_form_thanks.html
{% extends 'base2.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Page de remerciements pour une demande de chat video sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Merci de votre demande de chat vidéo{% endblock %}</title>
{% endblock %}

{% block main_content %}
<div class="outer-frame-politique">
    <div class="inner-frame-politique">
        <main class="politique-main">
            <div class="politique-border">

                <!--titre -->
                <h1 class="politique-title">Remerciements de votre demande de chat vidéo</h1>

                <!-- Section : Mise à jour et retour -->
                <div class="politique-header">
                    <a href="{{ url_for('landing_page') }}" class="politique-home-link">Retour à l'accueil</a>
                </div>
            </div>

            <!-- Séparation -->
            <hr class="politique-divider">

            <!-- Logo -->
            <div class="politique-logo">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}"
                     alt="Logo de SethiarWorks"
                     class="politique-logo-img">
            </div>

            <!-- Contenu principal -->
            <div class="contact-content">

                <!-- Carte de visite SethiarWorks -->
                <div class="cart-sethiar">
                    <!-- Verso -->
                    <img src="{{ url_for('static', filename='images/images_sethiarworks/cart_sethiar.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="sethiarcart-pic-contact">

                    <!-- Recto -->
                    <img src="{{ url_for('static', filename='images/images_sethiarworks/cart_sethiar2.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="sethiarcart-pic-contact">
                </div>
            </div>

            <div class="annonce">
                <p>
                    Nous vous remercions pour votre demande de chat vidéo et nous reviendrons très bientôt
                    vers vous afin de vous informer de notre réponse concernant votre demande.
                </p>

                <div class="space2"></div>

                <p>
                    Nous vous contacterons sous trois jours en vous précisant le jour, l'heure 
                    ainsi que le lien de connexion de notre visio.
                </p>
            
                <div class="space2"></div>
        
                <p>
                    Cordialement, l'équipe de SethiarWorks.
                </p>
            </div>
        
        </main>
    </div>
</div>
{% endblock %}
{% block footer_content %}
{% endblock %}

templates/chat/chat_session_admin.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Whereby Meeting</title>
</head>
<body>
    <h1>Rejoignez la réunion Whereby</h1>
    <!-- Intégrer Whereby via iframe -->
    <iframe src="{{ room_url }}" allow="camera; microphone; fullscreen" style="width: 100%; height: 600px; border: 0;"></iframe>
</body>
</html>

templates/chat/chat_session_user.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Whereby Meeting</title>
</head>
<body>
    <h1>Rejoignez la réunion Whereby</h1>
    <!-- Intégrer Whereby via iframe -->
    <iframe src="{{ room_url }}" allow="camera; microphone; fullscreen" style="width: 100%; height: 600px; border: 0;"></iframe>
</body>
</html>

templates/chat/form_request_chat.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Formulaire permettant de demander un chat vidéo avec l'administrateur du site entreprise SethiarWorks.">
<title>{% block title %}Formulaire de demande de chat avec <b>SethiarWorks</b>>{% endblock %}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">

        <div class="space-form"></div>

        <!--Titre premier de la section du chat vidéo.-->
        <h1 class="h1-devis">
            Informations concernant la demande de chat vidéo
        </h1>

        <div class="space"></div>

        <div class="annonce">
            
            <!-- Présentation -->
            <p>
                En remplissant ce formulaire, vous pourrez vous entretenir avec un membre de notre équipe.
            </p>

            <div class="space-annonce"></div>


            <p>   
                Vous pourrez alors librement expliciter <b>votre besoin</b> et profiter de <b>notre expertise</b>.
            </p> 

            <div class="space-annonce"></div>
            
            <p>
                Nous espérons vous revoir bientôt.
            </p>

            <div class="space-annonce"></div>

        </div>

        <form method="POST" action="{{ url_for('chat.send_request') }}" class="form-base"
              enctype="multipart/form-data">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <div class="space-form"></div>

            <!-- Titre du formulaire -->
            <h3 class="h3-form">Demande de chat vidéo</h3>
            
            <div class="space-form"></div>

            <!-- Token CSRF pour la sécurité -->
            {{ formrequest.csrf_token }}

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Champ pour le nom de l'entreprise -->
                <div class="form-group">
                    {{ formrequest.enterprise_name.label }}
                    {{ formrequest.enterprise_name() }}
                    {% if formrequest.enterprise_name.errors %}
                    <ul>
                        {% for error in formrequest.enterprise_name.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour l'email -->
                <div class="form-group">
                    {{ formrequest.email.label }}
                    {{ formrequest.email() }}
                    {% if formrequest.email.errors %}
                    <ul>
                        {% for error in formrequest.email.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour le contenu de requête -->
                <div class="form-group">
                    {{ formrequest.request_content.label }} {{ formrequest.request_content(rows=20, cols=20) }}
                    {% if formrequest.request_content.errors %}
                    <ul>
                        {% for error in formrequest.request_content.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour la date de visio -->
                <div class="form-group">
                    {{ formrequest.date_rdv.label }} {{ formrequest.date_rdv() }}
                    {% if formrequest.date_rdv.errors %}
                    <ul>
                        {% for error in formrequest.date_rdv.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour la date de visio -->
                <div class="form-group">
                    {{ formrequest.heure.label }}
                    {{ formrequest.heure() }}
                    {% if formrequest.heure.errors %}
                    <ul>
                        {% for error in formrequest.heure.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

            </div>
            
            <div class="separation1"></div>

            <div class="space-form"></div>

            <!-- Conteneur des boutons du formulaire -->
            <div class="container-btn">
                <button type="submit" class="validated-btn" aria-label="Valider la visio">
                    Validation de la demande
                </button>
                <a href="{{ url_for('landing_page') }}" class="cancelled-btn">
                    Annulation de la demande
                </a>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr("input[type='time']", {
            enableTime: true,
            noCalendar: true,
            dateFormat: "H:i",
            time_24hr: true
        });
    });

</script>

{% endblock %}