app/forms/subject_comment.py
"""
Code fournissant les formulaires concernant les sujets de l"'espace de commentaires du site de l'entreprise SethiarWorks.
"""

#==========================================================================================#
# Enregistrement d'un nouveau sujet de commentaire / Suppression d'un sujet de commentaire #
#==========================================================================================#

from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, HiddenField
from wtforms.validators import DataRequired


# Formulaire permettant la création d'un nouveau sujet sur l'espace de commentaires.
class NewSubjectCommentForm(FlaskForm):
    """
    Formulaire pour ajouter un nouveau sujet sur l'espace de commentaires.

    Attributes:
        nom (StringField) : Champ pour le nom du sujet pour l'espace de commentaires.

    Example :
        form = NewSubjectCommentForm()
    """
    # Nom du sujet.
    name = StringField(
        "Ajouter un nouveau sujet",
        validators=[DataRequired()],
        render_kw={'placeholder': "Nouveau sujet"}
    )

    # Action de soumettre le formulaire.
    submit = SubmitField("Ajouter le sujet")
    
    # Token de sécurité.
    csrf_token = HiddenField()


# Formulaire permettant de supprimer un sujet de l'espace de commentaires.
class SuppressSubject(FlaskForm):
    """
    Formulaire pour supprimer un sujet de la section espace de commentaires.

    Attributes :
        subject_id (HiddenField) : Champ caché pour l'ID du sujet à supprimer.
        submit (SubmitField): Bouton de soumission du formulaire.
    """
    # Champ caché pour l'id du sujet.
    subject_id = HiddenField(
        'Subject_id',
        validators=[DataRequired()]
    )

    # Action de soumettre le formulaire.
    submit = SubmitField('Supprimer')

    # Token de sécurité.
    csrf_token = HiddenField()

app/frontend/__init__.py
"""
Code permettant de définir l'accès aux routes concernant le frontend du site.
"""
from flask import Blueprint

frontend_bp = Blueprint('frontend', __name__)


# Import des routes pour le blueprint frontend
from app.frontend import routes  

app/frontend/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du site du frontend.
"""
import uuid 

from flask import render_template, abort


from flask_login import current_user

from app.frontend import frontend_bp

from app.forms.subject_comment import NewSubjectCommentForm
from app.forms.form_comment import CommentForm
from app.forms.form_comment import SuppressCommentForm
from app.forms.form_comment import SuppressCommentReply

from app.Models.subject import Subject, SubjectStatus

from app.Models.comment import Comment, CommentStatus

from app.Models.reply_comment import ReplyComment

from app.Models.reply_anonymous_comment import ReplyAnonymousComment, ReplyAnonymousCommentStatus

from app.Models.reply_anonymous_user_comment import ReplyAnonymousUserComment, ReplyAnonymousUserCommentStatus

from app.Models.reply_user_anonyme_comment import ReplyUserAnonymousComment


# Route permettant d'accéder à la zone des commentaires du site.
@frontend_bp.route('acces-commentaires')
def comments():
    """
    Route permettant d'accéder à l'espace commentaires du site.

    :return: templates HTML 'frontend/comments.html.
    """
    # Instanciation du formulaire.
    formsubjectcomment = NewSubjectCommentForm()
    
    # Récupération de tous les sujets validés.
    subjects = Subject.query.filter_by(status=SubjectStatus.VALIDE)

    # Passage de la valuer booléenne d'authentification.
    is_authenticated = current_user.is_authenticated

    # Debug : Vérification du type.
    print("Type of is_authenticated : ", type(is_authenticated))

    return render_template('frontend/comments.html', formsubjectcomment=formsubjectcomment,
                           subjects=subjects, is_authenticated=is_authenticated)


# Route afin de visualiser un sujet de l'espace de commentaires particulier.
@frontend_bp.route("/acces-sujet-comment/<int:subject_id>", methods=['GET', 'POST'])
def subject_comment(subject_id):
    """
    Route permettant d'accéder à un sujet de commentaire spécifique de l'espace commentaires.

    Args:
        subject_id (int) : L'identifiant du sujet à afficher.

    Returns :
        Template HTML 'frontend/subject_comments.html' avec les détails du sujet et ses commentaires associés.

    Raises :
        404 error : Si aucun sujet correspondant à l'ID spécifié n'est trouvé dans la base de données.
    """
    subject = Subject.query.get_or_404(subject_id)
    
    # Création de l'instance des formulaires.
    formcomment = CommentForm()
    formsuppress = SuppressCommentForm()
    formsuppressreply = SuppressCommentReply()
    formsubject = NewSubjectCommentForm()
    
    # Récupération des commentaires associés à ce sujet.
    comment = Comment.query.filter_by(
        subject_id=subject_id, 
        status=CommentStatus.VALIDE
        ).all()
    
    # Récupération des réponses authentifiés à un commentaire authentifié.
    replies = {
        comment.id: ReplyComment.query.filter_by(
            comment_id=comment.id
        ).all()
        for comment in comment
    }
    
    # Récupération des réponses anonymes associées à un commentaire anonyme.
    anonymous_replies = {
        comment.id: ReplyAnonymousComment.query.filter_by(
            comment_id=comment.id,
            status=ReplyAnonymousCommentStatus.VALIDEE
        ).all()
        for comment in comment
    }
    
    # Récupération des réponses anonymes associées à des commentaires d'authentifiés.
    anonymous_user_replies = {
        comment.id: ReplyAnonymousUserComment.query.filter_by(
            comment_id=comment.id,
            status=ReplyAnonymousUserCommentStatus.VALIDEE
        ).all()
        for comment in comment
    }
    
    # Récupération des réponses d'authentifiés à des commentaires d'anonymes.
    user_anonymous_replies = {
        comment.id: ReplyUserAnonymousComment.query.filter_by(
            comment_id=comment.id,
        ).all()
        for comment in comment
    }
    
    return render_template("frontend/subject_comments.html", 
                           subject=subject, subject_id=subject_id, user_id=current_user.id if current_user.is_authenticated else str(uuid.uuid4()),
                           formsuppress=formsuppress, formsuppressreply=formsuppressreply, 
                           formsubject=formsubject, comment=comment,
                           replies=replies,
                           anonymous_replies=anonymous_replies, anonymous_user_replies=anonymous_user_replies,
                           user_anonymous_replies=user_anonymous_replies,
                           formcomment=formcomment, is_authenticated=current_user.is_authenticated
                           )

templates/frontend/accueil.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Site de l'entreprise SethiarWorks d'Arnaud Lefetey.">
<title>{% block title %}SethiarWorks{% endblock %}</title>

<!-- CSS Principal -->
<link rel="stylesheet" href="{{ url_for('static', filename='gen/style.css') }}?v=1.0">
{% endblock %}

{% block header_content %}
{% endblock %}

{% block main_content %}
<!-- Conteneur principal -->
<div class="main-content">

    <!-- Conteneur logo -->
    <div class="logo-animation" id="logo">
        <div class="sprite sprite1"></div>
        <div class="sprite sprite2"></div>
        <div class="sprite sprite3"></div>
        <div class="sprite sprite4"></div>
        <div class="sprite sprite5"></div>
        <div class="sprite sprite6"></div>
        <div class="sprite sprite7"></div>
        <div class="sprite sprite8"></div>

        <button id="btn-logo" class="btn-secondary" onclick="restartAnimation()">Rejouer l'animation</button>
    </div>
    <!--Conteneur titre -->
    <div class="separation1"></div>

    <div class="space2"></div>

    <div class="title-container-landing">
        <p>Bienvenue sur le site de l'entreprise <i><b>SethiarWorks</b></i></p>
    </div>

    <div class="space2"></div>

    <div class="separation1"></div>

    <div class="space"></div>

    <section class="content-section-landing">
        
        <div class="outer-frame">
            
            <div class="inner-frame">
                
                <!-- Logo de SethiarWorks -->
                <div id="SethiarCart-pic" class="sethiarcart-pic">
                    <img src="{{ url_for('static', filename='images/images_sethiarworks/cart_sethiar.png') }}"
                         alt="Image représentant l'entreprise SethiarWorks">
                </div>

                <div class="space"></div>

                <p class="intro-landing">
                    Bonjour, vous voici sur le site de l'entreprise SethiarWorks.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Notre entreprise crée des solutions numériques sur mesure, adaptées à vos besoins.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Notre objectif est de vous accompagner dans la réalisation de vos projets web.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Cela permet de continuellement perfectionner les compétences de l'équipe de développement à travers
                    les multiples attentes de notre clientèle dans la création et le développement de votre projet.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Répondre à vos attentes est notre priorité.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Chaque retour de nos clients nous permet d'affiner notre approche afin de
                    vous offrir des solutions toujours plus adaptées.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Chaque client est différent, ce qui fait que chaque projet possède une unicité et une originalité
                    que nous
                    chercherons à personnaliser au sein d'une réalisation.
                </p>

                <div class="space"></div>

                <p class="intro-landing">
                    Cela marquera non seulement notre manière de coder, mais surtout,
                    sera le reflet du besoin de ce que <b>vous</b>, en tant que client, voulez mettre en avant.
                </p>
            </div>
        </div>
    </section>

    <div class="space"></div>

    <!--Slogan de SethiarWorks -->
    <div class="slogan-container">
        <p class="slogan-text">
            Donner vie à votre imaginaire, c'est ce que nous savons faire
        </p>
    </div>

    <div class="space"></div>

    <div id="registration" class="registration-wrapper">
        <div class="outer-frame-registration">
            <div class="inner-frame-registration">
                <!-- Enregistrement possible ici -->
                <div class="registration-landing">
                    <p class="registration-sentence-landing">
                        N'hésitez pas à demander un devis afin de donner vie à votre projet.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="space"></div>

    <div class="separation1"></div>
    
    <div class="space"></div>

    <!-- Section des produits du Site -->

    <section id="products" class="products">
        <h1 class="product-h1">Produits développés par l'entreprise SethiarWorks</h1>
        
        <!-- Swiper container -->
        <div class="swiper-container">
            <div class="swiper-wrapper">

                <!-- Slide 1 : Développement sur mesure -->
                <div class="swiper-slide product-card">
                    <h3>Développement sur mesure</h3>
                     
                    <div class="space"></div>
                    
                    <div class="product-pic">
                        <img src="{{ url_for('static', filename='images/images_produit/dev-web.png') }}"
                             alt="Image représentant le développement et la conception d'application">
                    </div>
                    <div class="space-product"></div>
                    <div class="space"></div>

                    <h4>Applications Web :</h4>
                    <div class="product-p">
                        <p>Sites modernes et responsives, adaptés aux besoins de votre entreprise.</p>
                        <p>Développement de blogs professionnels avec gestion de contenu simplifiée.</p>
                        <p>Conception de sites de vente en ligne avec intégration de systèmes de paiement sécurisés.</p>
                        <p>Création d’applications Django, Flask, ou FastAPI adaptées aux besoins des clients.</p>
                    </div>

                    <div class="space"></div>

                    <h4>Scripts automatisés :</h4>
                    <div class="product-p">
                        <p>Automatisation de tâches répétitives (ex. : extraction de données, génération de
                            rapports).</p>
                    </div>

                    <div class="space"></div>

                    <h4>Applications d’analyse de données :</h4>
                    <div class="product-p">
                        <p>Développement d’outils pour manipuler, analyser et visualiser des données avec Python
                            (pandas,
                            Matplotlib, Dash).</p>
                    </div>
                </div>

                <!-- Slide 2 : Consulting technique -->
                <div class="swiper-slide product-card">
                    <h3>Consulting technique</h3>
                    
                    <div class="space"></div>

                    <div class="product-pic">
                        <img src="{{ url_for('static', filename='images/images_produit/consulting.png') }}"
                             alt="Image représentant le consulting et l'analyse">
                    </div>
                    <div class="space-product"></div>
                    <div class="space"></div>
                    
                    <div class="product-p">
                        <p>Analyse des besoins techniques d’un projet.</p>
                        <p>Recommandations sur l’architecture, les outils, ou les technologies Python à utiliser.</p>
                        <p>Audit et optimisation de code existant.</p>
                    </div>
                </div>

                <!-- Slide 3 : Maintenance et support -->
                <div class="swiper-slide product-card">
                    <h3>Maintenance et support</h3>

                    <div class="space"></div>

                    <div class="product-pic">
                        <img src="{{ url_for('static', filename='images/images_produit/maintenance.png') }}"
                             alt="Image représentant la maintenance">
                    </div>
                    <div class="space-product"></div>
                    <div class="space"></div>

                    <div class="product-p">
                        <p>Résolution de bugs dans des applications existantes.</p>
                        <p>Amélioration de la performance d’une application.</p>
                        <p>Migration vers des technologies modernes.</p>
                    </div>
                </div>

                <!-- Slide 4 : Templates et outils -->
                <div class="swiper-slide product-card">
                    <h3>Templates et outils</h3>

                    <div class="space"></div>

                    <div class="product-pic">
                        <img src="{{ url_for('static', filename='images/images_produit/templating.png') }}"
                             alt="Image représentant la création de templates">
                    </div>
                    <div class="space"></div>
                    <div class="space-product"></div>

                    <h4>Scripts préconstruits :</h4>
                    <div class="product-p">
                        <p>Scripts pour extraire des données d’un site (web scraping avec BeautifulSoup/Scrapy).</p>
                        <p>Gestion d’API REST.</p>
                        <p>Générateur de rapports Excel/CSV automatisés.</p>
                    </div>

                    <div class="space"></div>

                    <h4>Templates de projet Python :</h4>
                    <div class="product-p">
                        <p>Boilerplate pour des projets Django, Flask ou FastAPI.</p>
                    </div>

                    <div class="space"></div>

                    <h4>Dashboards ou applications clés en main :</h4>
                    <div class="product-p">
                        <p>Dashboards interactifs avec Plotly/Dash ou Streamlit pour les entreprises.</p>
                    </div>

                    <div class="space"></div>

                    <h4>Gestion simplifiée :</h4>
                    <div class="product-p">
                        <p>Outils comme un gestionnaire de tâches, un CRM de base ou une application de facturation.</p>
                    </div>
                </div>

                <!-- Slide 5 : Produits SaaS -->
                <div class="swiper-slide product-card">
                    <h3>Produits SaaS</h3>

                    <div class="space"></div>

                    <div class="product-pic">
                        <img src="{{ url_for('static', filename='images/images_produit/saas.png') }}"
                             alt="Image représentant la création de Saas">
                    </div>
                    <div class="space-product"></div>
                    <div class="space"></div>

                    <h4>Micro-SaaS :</h4>
                    <div class="product-p">
                        <p>Une application en ligne qui utilise Python pour résoudre un problème précis.</p>
                    </div>

                    <div class="space"></div>
                    
                    <h4>API :</h4>
                    <div class="product-p">
                        <p>Une API facile à intégrer pour des tâches spécifiques (ex. : nettoyage ou formatage de
                            données).</p>
                    </div>
                </div>

            </div>

            <!-- Pagination -->
            <div class="swiper-pagination"></div>

            <!-- Flèches de navigation -->
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
        </div>
    </section>

    <!-- Initialisation de la modale pour carrousel -->
    <div id="slide-modal" class="modal">
        <div class="modal-content">
            <span class="close-button">&times;</span>
            <img id="modal-image" src="" alt="Image agrandie du slide">
            <h3 id="modal-title"></h3>
            <p id="modal-description"></p>
        </div>
    </div>
</div>
{% endblock %}

templates/frontend/comments.html
{% extends 'base.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Forum du site permettant de discuter, interagir et donner son avis sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Bienvenue sur le forum du blog{% endblock %}</title>

<!-- CSS Principal -->
<link rel="stylesheet" href="{{ url_for('static', filename='gen/style.css') }}?v=1.0">
{% endblock %}

{% block header_content %}
{% endblock %}

{% block main_content %}

<!-- conteneur principal -->
<div class="main-content">

    <!-- cadre extérieur -->
    <div class="outer-frame-politique">

        <!-- cadre intérieur -->
        <div class="inner-frame-politique">

            <!-- division de retour à la page d'accueil -->
            <div class="back-link-comment">
                <a class="btn-primary desktop-only" href="{{ url_for('landing_page') }}">
                    Retour à la page d'accueil
                </a>
                
                <!-- Version icône (<768px) -->
                <a class="btn-icon mobile-only" href="{{ url_for('landing_page') }}">
                    <img src="{{ url_for('static', filename='icons/home_1.svg') }}" 
                    alt="Retour à l'accueil">
                </a>
            </div>
            
            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='Images/images_accueil/logo_png.png') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <div class="space-form"></div>

            <!--titre -->
            <h1 class="comment-title">Espace de commentaires</h1>

            <div class="space-form"></div>
            
            <!-- division pour image forum -->
            <div class="comment-image-container">

                <!-- image centrale -->
                <div class="image-comment">
                    <img src="{{ url_for('static', filename='images/images_comment/comment1.png') }}"
                         alt="Image comment">
                </div>
            </div>

            <div class="space-form"></div>
            
            <!-- Séparation -->
            <hr class="politique-divider">

            <!-- Conteneur d'ajout de catégories -->
            <div class="form-container">
                <!-- Formulaire d'ajout de sujet pour connecté -->
                <form method="POST" action="{{ url_for('user.add_subject_comment') }}">

                    <!-- Token CSRF pour la sécurité -->
                    {{ formsubjectcomment.csrf_token }}
                    
                    <div class="form flex-container">
                        <!-- Champ pour le nouveau sujet -->
                        <div class="field">
                            {{ formsubjectcomment.name.label }}
                            {{ formsubjectcomment.name(size=20) }}
                        </div>
                    
                        <!-- Conteneur du bouton de soumission au sujet -->
                        <div class="container-btn-comment">
                            <button type="submit" class="btn-icon">
                                <img src="{{ url_for('static', filename='icons/plus_1.svg') }}" alt="Envoyer">            
                            </button>  
                        </div>
                    </div>
                </form>  
            </div>

            <div class="space2"></div>

            <!-- Liste des sujets -->
            <div class="subjects-container">
                <h4 class="section-title">Sujets disponibles</h4>

                <!--tableau des sujets -->
                <table class="subjects-table">
                    <thead>
                    <tr>
                        <th>Sujet</th>
                        <th>Auteur</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for subject in subjects %}
                        <tr>
                            <td>{{ subject.name }}</td>
                            <td>{{ subject.author_display }}</td>
                            <td>
                                <a href="{{ url_for('frontend.subject_comment', subject_id=subject.id) }}"
                                    class="btn-secondary">
                                        Voir
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer_content %}

{% endblock %}