app/forms/user_login.py
"""
Code permettant de se connecter en tant qu'utilisateur.
"""

#--------------------------------#
# Connexion Utilisateur / Client #
#--------------------------------#

from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField, HiddenField

from wtforms.validators import DataRequired


class UserConnection(FlaskForm):
    """
    Formulaire de connexion pour les clients de l'entreprise afin de laisser un commentaire.
    
    Attributes:
        name_enterprise (StringField): Champ pour le pseudo du client utilisateur.
        password (PasswordField): Champ pour le password de l'utilisateur.
        submit (SubmitField): Bouton de soumission du commentaire.
        csrf_token (HiddenField): Jeton CSRF pour la sécurité des formulaires.
    """
    
    # Champ pour le nom d'entreprise.
    enterprise_name = StringField(
        "Nom de l'entreprise",
        validators=[DataRequired()],
        render_kw={"placeholder": "Nom entreprise"}
    )
    
    # Champ pour le password.
    password = PasswordField(
        "Mot de passe",
        validators=[DataRequired()],
        render_kw={'placeholder': "Mot de passe"}
    )
    
    # Action de soumettre le formulaire.
    submit = SubmitField("Se connecter")
    
    # Jeton CSRF pour la sécurité du formulaire.
    csrf_token = HiddenField()
    
    

app/devis/__init__.py
"""
Code permettant de définir l'acès aux routes concernant les demandes de devis du site.
"""

from flask import Blueprint

devis_bp = Blueprint('devis', __name__)

from app.devis import routes  # Import des routes pour le blueprint devis

app/devis/routes.py
"""
Code permettant de gérer les demandes de devis
"""

from app.devis import devis_bp

from flask import flash, redirect, url_for
from app import db

from app.mail.routes import mail_reply_devis_reject, mail_reply_devis_validate

from app.Models.devis_request import DevisRequest


# Méthode supprimant la demande de chat vidéo du tableau administrateur.
@devis_bp.route('/suppression-demande-devis/<int:id>', methods=['POST'])
def suppress_devis(id):
    """
    Supprime une demande de devis du tableau des demandes administratives.

    Cette route permet à l'administrateur de supprimer une demande de devis spécifique en fonction de son ID.
    Après la suppression, un message de confirmation est affiché et l'administrateur est redirigé vers la
    page de la liste des devis du site.

    Args:
        id (int): L'identifiant unique de la demande de devis à supprimer.

    Returns:
        Response: Redirection vers la page de la liste des devis après la suppression du devis.
    """
    try:
        # Récupération du devis à supprimer.
        devis = DevisRequest.query.get(id)

        # Vérification de l'existence du devis.
        if not devis:
            flash("La demande de devis n'a pas été trouvée.", "danger")
            return redirect(url_for('admin.list_devis'))

        # Suppression du devis.
        db.session.delete(devis)

        # Enregistrement au sein de la base de données.
        db.session.commit()

        # Message de confirmation après la suppression.
        flash(f"La requête de l'utilisateur : {devis.nom} {devis.prenom} a été supprimée.", "success")

    except Exception as e:
        # Gestion des erreurs et annulation des changements si nécessaire.
        db.session.rollback()  # Annulation des modifications en cas d'erreur.
        flash(f"Une erreur s'est produite lors de la suppression : {str(e)}", "danger")

    finally:
        # Fermeture de la session de base de données.
        db.session.close()

    return redirect(url_for('admin.list_devis'))


# Méthode générique pour traiter une demande de devis.
def process_devis(id, action):
    """
    Traite une demande de devis en fonction de l'action spécifiée (valider ou refuser)
    et en informe l'utilisateur par e-mail.

    Args:
        id (int): L'identifiant unique de la demande de devis.
        action (str): L'action à effectuer, soit "valider" ou "refuser".

    Returns:
        Response: Redirection vers la page de la liste des devis après traitement.
    """
    # Récupération de la demande de devis.
    devis = DevisRequest.query.get_or_404(id)

    try:
        # Mise à jour du statut selon l'action.
        if action == "valider":
            devis.accept_devis_request()
            mail_reply_devis_validate(devis)
            flash("La demande de devis a été traitée et validée.", "success")
        elif action == "refuser":
            devis.refuse_devis_request()
            mail_reply_devis_reject(devis)
            flash("La demande de devis a été traitée et refusée.", "success")
        else:
            flash("Action inconnue pour traiter la demande.", "danger")
            return redirect(url_for("admin.list_devis"))

        # Sauvegarde des modifications dans la base de données.
        db.session.commit()

    except Exception as e:
        # Gestion des erreurs lors du traitement.
        flash(f"Une erreur s'est produite : {str(e)}", "danger")
        # Annule les changements si une erreur survient.
        db.session.rollback()

    finally:
        # Fermeture de la session de base de données.
        db.session.close()

    return redirect(url_for("admin.list_devis"))


# Route pour valider une demande de devis.
@devis_bp.route('/validation-demande-devis/<int:id>', methods=['POST'])
def valide_devis(id):
    """

    :param id:
    :return:
    """
    return process_devis(id, "valider")


# Route pour refuser une demande de devis.
@devis_bp.route('/refus-demande-devis/<int:id>', methods=['POST'])
def refuse_devis(id):
    """

    :param id:
    :return:
    """
    return process_devis(id, "refuser")

app/user/__init__.py
"""
Code permettant de définir l'accès aux routes concernant les fonctions utilisateurs du site.
"""

from flask import Blueprint

user_bp = Blueprint('user', __name__)


# Import des routes pour le blueprint user
from app.user import routes  

app/user/routes.py
"""
Code permettant de définir les routes concernant les fonctions des utilisateurs du blog comme l'enregistrement
et l'accès aux formulaires.
"""
import uuid

from datetime import datetime

from app.user import user_bp

from app.Models import db

from flask import render_template, redirect, url_for, request, flash, session
from flask_login import login_required, current_user


from app.forms.devis_request import DevisRequestForm
from app.forms.form_comment import CommentForm, ChangeCommentForm, SuppressCommentForm, \
    ReplyCommentForm, ChangeCommentReply, SuppressCommentReply

from app.forms.subject_comment import NewSubjectCommentForm

from app.Models.user import User
from app.Models.subject import Subject, SubjectStatus
from app.Models.comment import Comment
from app.Models.reply_comment import ReplyComment

from app.Models.comment import Comment, CommentStatus

from app.Models.reply_anonymous_comment import ReplyAnonymousComment, ReplyAnonymousCommentStatus

from app.Models.reply_user_anonyme_comment import ReplyUserAnonymousComment

from app.Models.reply_anonymous_user_comment import ReplyAnonymousUserComment, ReplyAnonymousUserCommentStatus
from app.Models.devis_request import DevisRequest

from app.mail.routes import mail_reply_comment, \
    send_mail_validate_demand, send_mail_inform_demand



# Méthode permettant de visualiser la photo de l'utilisateur.
@user_bp.route("/profil_photo/<int:user_id>")
def profil_photo(user_id):
    """
    Affiche la photo de profil d'un utilisateur ou une photo par defualt si anonyme.

    :param user_id : L'identifiant de l'utilisateur.

    :return : L'image de la photo de profil en tant que réponse HTTP avec le type MIME approprié.
    """
    user = User.query.get_or_404(user_id)
    if user.profil_photo:
        return user.profil_photo, {'Content-Type': 'image/jpeg'}
    else:
        return "No image found", 404



# Route permettant de renvoyer la photo de profil par défaut pour les utilisateurs anonymes.
@user_bp.route('/static/images/images_profil/default_profile_photo.png')
def profil_photo_anonymous():
    return url_for('static', filename='images/images_profil/default_profile_photo.png')


# route qui va permettre à un sujet connecté ou non de créer un sujet.
@user_bp.route("/comment/ajouter-sujet", methods=['POST'])
def add_subject_comment():
    """
    Permet à un utilisateur (connecté ou non) de créer un sujet.
    
        - Connecté --> Création du sujet dans l'espace de commentaire.
        - Anonyme --> En attende de validation par l'admin.
    """
    # Instanciation du formulaire.
    form = NewSubjectCommentForm()

    if form.validate_on_submit():
        # Utilise la méthode statique propre du modèle Subject
        subject = Subject.create(
            name=form.name.data,
            user=current_user if current_user.is_authenticated else None
        )
        
        # Ajout dans la base de données.
        db.session.add(subject)
        try:
            # Enregistrement dans la base de données.
            db.session.commit()
            if subject.is_anonymous:
                flash("Votre sujet a été soumis et est en attente de validation.", "info")
            else:
                flash("Sujet créé avec succès.", "success")
        except Exception as e:
            db.session.rollback()
            flash("Une erreur est survenue lors de l'ajout du sujet.", "error")
            print("Erreur lors de l'ajout du sujet :", e)

    return redirect(url_for('frontend.comments'))         
    

# Route permettant à un utilisateur connecté ou non de poster un commentaire.
@user_bp.route("/commentaires", methods=['POST'])
def comment_enterprise():
    """
    Permet à un utilisateur, connecté ou non, de laisser un commentaire.

    Returns :
         redirect : Redirige vers la page d'accueil après avoir laissé un commentaire.
    """
    # Récupération du contenu du commentaire.
    comment_content = request.form.get("comment_content")
    subject_id = request.form.get("subject_id")

    # Vérification que le contenu du commentaire existent.
    if not comment_content or not subject_id:
        flash("Le contenu du commentaire ou le sujet est manquant.", "error")
        return redirect(url_for("frontend.comments"))
    
    try:
        subject_id = int(subject_id)
    except ValueError:
        flash("Sujet invalide.", "error")
        return redirect(url_for("frontend.comments"))
    
    # Recherche du sujet dans la table Subject.
    subject = Subject.query.get(subject_id)
    if not subject or subject.status != SubjectStatus.VALIDE:
        flash("Sujet introuvable ou non validé.", "error")
        return redirect(url_for("frontend.comments"))

    # Gestion de l'anonymat
    anonymous_id = None
    if not current_user.is_authenticated:
        if "anonymous_id" not in session:
            session["anonymous_id"] = str(uuid.uuid4())
        anonymous_id = session["anonymous_id"]

    # Création du commentaire
    new_comment = Comment.create(
        comment_content=comment_content,
        subject=subject,
        user=current_user if current_user.is_authenticated else None,
        anonymous_id=anonymous_id
    )
    
    # Ajout dans la base de données.
    db.session.add(new_comment)
    try:
        # Enregistrement de la base de données.
        db.session.commit()
        flash("Commentaire soumis avec succès.", "success" if not new_comment.is_anonymous else "info")
    except Exception as e:
        db.session.rollback()
        print("Erreur lors de l'enregistrement du commentaire :", e)
        flash("Une erreur est survenue. Veuillez réessayer.", "error")
        return redirect(url_for("frontend.comments"))

    return redirect(url_for("frontend.subject_comment", subject_id=subject_id,
                            user_enterprise_name=new_comment.author_enterprise_name))


# Route permettant à un utilisateur connecté de modifier son commentaire.
@user_bp.route('/modification-commentaire-utilisateur/<int:id>', methods=['GET', 'POST'])
@login_required
def change_comment(id):
    """
    Permet à un utilisateur connecté de modifier son commentaire.
    N'autorise que l'auteur du commentaire à le modifier. Mais si l'utilisateur est anonyme,
    il ne peut modifier son commentaire.

    Args:
        id (int): L'id du commentaire à modifier.

    Returns:
        redirect: Redirige vers la page des commentaires.
    """
    comment = Comment.query.filter_by(id=id).first_or_404()

    # Vérification que l'utilisateur actuel est l'auteur du commentaire.
    if comment.author_user_id != current_user.id and comment.anonymous_id != session.get('anonymous_id'):
        flash('Vous n\'êtes pas autorisé à modifier ce commentaire.')
        return redirect(url_for('frontend.forum_subject'))

    formchange = ChangeCommentForm(obj=comment)

    if formchange.validate_on_submit():
        comment.comment_content = formchange.comment_content.data
        db.session.commit()
        flash('Commentaire modifié avec succès.')
        return redirect(url_for('frontend.comments'))
    else:
        flash('Erreur lors de la validation du commentaire.')

    return render_template('user/edit_comment.html', formchange=formchange, comment=comment)


# Route permettant à un utilisateur connecté de supprimer son commentaire.
@user_bp.route('/suppression-commentaire-utilisateur/<int:id>', methods=['POST'])
@login_required
def delete_comment(id):
    """
    Permet à un utilisateur connecté de supprimer son commentaire.
    N'autorise que l'auteur du commentaire à le supprimer. Mais si l'utilisateur est anonyme,
    il ne peut supprimer son commentaire.

    Args:
        id (int): L'id du commentaire à supprimer.

    Returns:
        redirect: Redirige vers la page des commentaires.
    """
    formsuppress = SuppressCommentForm()
    comment = Comment.query.filter_by(id=id).first_or_404()

    # Vérification que l'utilisateur actuel est l'auteur du commentaire.
    if comment.author_user_id != current_user.id and comment.anonymous_id != session.get('anonymous_id'):
        flash('Vous n\'êtes pas autorisé à supprimer ce commentaire.')
        return redirect(url_for('frontend.comments', comment=comment))

    db.session.delete(comment)
    db.session.commit()
    flash('Commentaire supprimé avec succès.')
    return redirect(url_for('frontend.comments', comment=comment))


# Route permettant à un utilisateur connecté ou non de répondre à un commentaire authentifié ou non.
@user_bp.route("/comment<int:comment_id>/reply_subject", methods=['GET', 'POST'])
def comment_replies(comment_id):
    """
    Permet à un utilisateur connecté ou non de répondre à un commentaire.
    """
    # Instanciation du formulaire.
    formreply = ReplyCommentForm()
    # Récupération de tous les commentaires.
    comment = Comment.query.get_or_404(comment_id)
    
    # Détermination du type de commentaire.
    comment_type = "anonymous" if comment.author_user_id is None else "customer"
    subject_id = comment.subject_id


    if formreply.validate_on_submit():

        reply_content = formreply.reply_content.data
        anonymous_id = session.get("anonymous_id")
        
        # Cas n°1 : utilisateur connecté.
        if current_user.is_authenticated:
            if comment_type == "customer":
                # Authentifié --> Authentifié.
                new_reply = ReplyComment(
                    reply_content=reply_content,
                    user_id=current_user.id,
                    comment_id=comment.id
                )    
            else:
                # Authentifié --> Anonyme.
                new_reply = ReplyUserAnonymousComment(
                    reply_content=reply_content,
                    user_id=current_user.id,
                    comment_id=comment.id,
                )    
                
        # Cas n°2 : Utilisateur anonyme.
        else:
            if not anonymous_id:
                # Génération d'un id au cas où.

templates/user/devis_form.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description"
      content="Obtenez rapidement un devis personnalisé pour votre projet avec SethiarWorks, expert en développement et conception numérique.">
<title>{% block title %}Demande de devis entreprise SethiarWorks{% endblock %}</title>
{% endblock %}

{% block body_content %}
<div class="outer-frame">
    <div class="inner-frame">

        <div class="space-form"></div>
        
        <h1 class="h1-devis">
            Informations concernant la demande de devis
        </h1>
        
        <div class="space"></div>

        <div class="annonce">

            <!-- Présentation -->
            <ul>
                <li><b>* Rapidité :</b> Réponse garantie sous une semaine.</li>
                <li><b>* Clarté :</b> Décrivez votre projet avec les fonctionnalités attendues.</li>
                <li><b>* Transparence :</b> Consultez nos <u><a href="{{url_for('functional.politique')}}">conditions
                    générales</a></u>.
                </li>
            </ul>
            <div class="space-form"></div>

            <!--Champ de précision -->
            <p>
                Pour tout renseignement supplémentaire, vous pouvez consulter 
                nos <u><a href="{{url_for('functional.mentions')}}">mentions légales</a></u>.
            </p>
        </div>

        <form method="POST" action="{{ url_for('user.user_devis_demand') }}" class="form-base"
              enctype="multipart/form-data">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}" alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <div class="space-form"></div>

            <!-- Titre du formulaire -->
            <h3 class="h3-form">Demande de devis</h3>

            <div class="space-form"></div>

            <!-- Token CSRF pour la sécurité -->
            {{ form_devis.csrf_token }}

            <!-- Conteneur des champs du formulaire -->
            <div class="form-container">

                <!-- Champ pour le nom et le prénom -->
                <div class="form-group">
                    {{ form_devis.lastname.label }} 
                    {{ form_devis.lastname() }}
                    {% if form_devis.lastname.errors %}
                    <ul>
                        {% for error in form_devis.lastname.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}

                    <div class="space-inter-form"></div>

                    {{ form_devis.firstname.label }} 
                    {{ form_devis.firstname() }}
                    {% if form_devis.firstname.errors %}
                    <ul>
                        {% for error in form_devis.firstname.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour le numéro de téléphone -->
                <div class="form-group">
                    {{ form_devis.phone.label }} 
                    {{ form_devis.phone() }}
                    {% if form_devis.phone.errors %}
                    <ul>
                        {% for error in form_devis.phone.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champs pour le nom de l'entreprise-->
                <div class="form-group">
                    {{ form_devis.enterprise_name.label }} 
                    {{ form_devis.enterprise_name() }}
                    {% if form_devis.enterprise_name.errors %}
                    <ul>
                        {% for error in form_devis.enterprise_name %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour l'email -->
                <div class="form-group">
                    {{ form_devis.email.label }} 
                    {{ form_devis.email() }}
                    {% if form_devis.email.errors %}
                    <ul>
                        {% for error in form_devis.email.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Champ pour le type de projet -->
                <div class="form-group">
                    <u>{{ form_devis.project_type.label }}</u>
                    
                    <div style="margin-bottom: 3%;"></div>
                    
                    <div class="checkbox-group">
                        {% for subfield in form_devis.project_type %}
                            <div style="margin-bottom: 3% ">
                                <label style="display: inline-block;">{{subfield.label }}</label>
                                <label style="display: inline-block; margin-left: 10px;">{{ subfield }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    {% if form_devis.project_type.errors %}
                    <ul>
                        {% for error in form_devis.project_type.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

                <div class="space-inter-form"></div>

                <!-- Conteneur du contenu de la demande de devis -->
                <div class="form-group">
                    {{ form_devis.devis_content.label }}
                    {{ form_devis.devis_content(class="form-control") }}
                    {% if form_devis.devis_content.errors %}
                    <ul>
                        {% for error in form_devis.demand_content.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>

            </div>

            <div class="separation1"></div>

            <div class="space-form"></div>

            <!-- Conteneur des boutons du formulaire -->
            <div class="container-btn">
                <button type="submit" class="validated-btn" aria-label="Valider la demande de devis">
                    Validation de la demande de devis
                </button>
                <a href="{{ url_for('landing_page') }}" class="cancelled-btn">Annulation et retour à l'accueil</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/devis_form_thanks.html
{% extends 'base2.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Page de remerciements pour une demande de devis sur le site de l'entreprise SethiarWorks.">
<title>{% block title %}Merci de votre demande de devis{% endblock %}</title>
{% endblock %}

{% block main_content %}
<div class="outer-frame-politique">
    <div class="inner-frame-politique">
        <main class="politique-main">
            <div class="politique-border">

                <!--titre -->
                <h1 class="information-title">Remerciements de votre demande de devis</h1>

                <!-- Section : Mise à jour et retour -->
                <div class="politique-header">
                    <a href="{{ url_for('landing_page') }}" class="btn-secondary">Retour à l'accueil</a>
                </div>
            </div>

            <!-- Séparation -->
            <hr class="politique-divider">

            <!-- Logo -->
            <div class="politique-logo">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}"
                     alt="Logo de SethiarWorks"
                     class="politique-logo-img">
            </div>

            <!-- Contenu principal -->
            <div class="contact-content">

                <!-- Carte de visite SethiarWorks -->
                <div class="cart-sethiar">
                    <!-- Verso -->
                    <img src="{{ url_for('static', filename='images/images_sethiarworks/cart_sethiar.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="sethiarcart-pic-contact">

                    <!-- Recto -->
                    <img src="{{ url_for('static', filename='images/images_sethiarworks/cart_sethiar2.png') }}"
                         alt="carte de visite de SethiarWorks"
                         class="sethiarcart-pic-contact">
                </div>
            </div>
          <div class="annonce">
            <p>
                Nous vous remercions pour votre demande de devis et nous reviendrons très bientôt
                vers vous afin de vous informer de notre réponse concernant votre demande.
            </p>

            <div class="space2"></div>

                <div class="resume-demand">

                </div>

                <div class="thanks-message">
                    <p>
                        Cordialement, l'équipe de SethiarWorks.
                    </p>
                </div>
        
        </main>
    </div>
</div>
{% endblock %}
{% block footer_content %}
{% endblock %}

templates/user/edit_comment.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Cadre externe -->
<div class="outer-frame">
    <!-- Cadre interne -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier un commentaire</h2>

        <form method="POST" action="{{ url_for('user.change_comment', id=comment.id) }}" class="form-base">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}"
                    alt="Logo de SethiarWorks"
                    class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchange.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification du commentaire -->
            <div class="form-group">
                {{ formchange.comment_content.label }} {{ formchange.comment_content() }}
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">
                <input type="hidden" name="comment_id" value="{{ comment.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la modification du commentaire">
                        Modifier le commentaire
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/edit_reply.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de modification d'une réponse à un commentaire par l'utilisateur.">
<title>{% block title %}Modification d'une réponse à un commentaire{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Cadre externe -->
<div class="outer-frame">
    <!-- Cadre interne -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour modifier une réponse à un commentaire.</h2>
        <form method="POST" action="{{ url_for('user.change_reply', id=reply.id) }}" class="form-base">

            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}"
                     alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Modification de la réponse du commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formchangereply.hidden_tag() }}

            <div class="space-form"></div>

            <!-- Conteneur de la modification de la réponse au commentaire -->
            <div class="form-group">
                {{ formchangereply.reply_content.label }} {{ formchangereply.reply_content() }}
                <input type="hidden" name="comment_id" value="{{ reply.subject_id }}">
                <input type="hidden" name="reply_id" value="{{ reply.id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la modification">Soumettre la
                        réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/user/reply_comment.html
{% extends 'baseform.html.jinja2' %}

{% block head_content %}
<meta name="description" content="Formulaire de réponse par un utilisateur au sujet posté sur l'espace de commentaires.">
<title>{% block title %}Réponse au sujet de l'espace de commentaires{% endblock %}</title>
{% endblock %}

{% block header_content %}

{% endblock %}

{% block body_content %}
<!-- Cadre externe -->
<div class="outer-frame">
    <!-- Cadre interne -->
    <div class="inner-frame">

        <!-- Titre du formulaire -->
        <h2 class="h2-form">Voici le formulaire pour écrire une réponse aux sujets postés sur l'espace de commentaires.</h2>

        <form method="POST" class="form-base"
              action="{{ url_for('user.comment_replies', comment_id=comment.id) }}">
            <!-- Image du logo -->
            <div class="imgcontainer-form">
                <img src="{{ url_for('static', filename='images/images_accueil/logo_png.png') }}"
                     alt="Logo de SethiarWorks"
                     class="avatar-form">
            </div>

            <!-- Titre de la section du formulaire -->
            <h3 class="h3-form">Réponse au commentaire</h3>

            <!-- hidden_tag pour génération du token CSRF pour la sécurité -->
            {{ formreply.csrf_token }}

            {{ formreply.comment_id(value=comment.id) }}
            
            <div class="space-form"></div>

            <!-- Conteneur de la réponse au commentaire -->
            <div class="form-group">
                {{ formreply.reply_content.label }} {{ formreply.reply_content() }}
                
                <input type="hidden" name="subject_id" value="{{ comment.subject_id }}">

                <div class="container-btn">
                    <button type="submit" class="validated-btn" aria-label="Valider la réponse">Soumettre la réponse
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}